/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;

/**
 *
 * @author thiag
 */
public class GUICadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadastro
     */
    public GUICadastro() {
        initComponents();
    }
    
    
            public void cadastrarUsuario(){
        
        try{

	modelo.UsuarioVO u = new modelo.UsuarioVO();

	u.setNome(jtfNome1.getText());
        u.setEmail(jtfEmail1.getText());
        u.setDataNasc(Integer.parseInt(jtfDataNasc1.getText()));
        u.setPeso(Double.parseDouble(jtfPeso1.getText()));
        u.setAltura(Double.parseDouble(jtfAltura1.getText()));
        u.setAlergias(jtfAlergias1.getText());
        u.setDoencas(jtfDoencas1.getText());
        
	// Chama o usuário serviços que fará a inserção dos dados da classe dentro do banco 
	servicos.UsuarioServicos us = servicos.ServicosFactory.getUsuarioServicos();
        
        us.cadastrarUsuario(u);

	JOptionPane.showMessageDialog(null,"Novo usuário cadastrado com sucesso! ", "Confirmação",JOptionPane.INFORMATION_MESSAGE);
	
}catch(Exception e){

	JOptionPane.showMessageDialog(null, "Ops, algo deu errado! "+e.getMessage(),"Erro!", JOptionPane.ERROR_MESSAGE);

}
	
}
            
            
    public void cancelar(){
        
    jtfNome1.setText(null);
    jtfEmail1.setText(null);
    jtfDataNasc1.setText(null);
    jtfPeso1.setText(null);
    jtfAltura1.setText(null);
    jtfDataNasc1.setText(null);
    jtfAlergias1.setText(null);
    jtfDoencas1.setText(null);
    
    }
            
            
            
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jlDataNasc = new javax.swing.JLabel();
        jtfDataNasc = new javax.swing.JTextField();
        jlPeso = new javax.swing.JLabel();
        jtfPeso = new javax.swing.JTextField();
        jlAltura = new javax.swing.JLabel();
        jtfAltura = new javax.swing.JTextField();
        jlAlergias = new javax.swing.JLabel();
        jtfAlergias = new javax.swing.JTextField();
        jlDoencas = new javax.swing.JLabel();
        jtfDoencas = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlNome1 = new javax.swing.JLabel();
        jtfNome1 = new javax.swing.JTextField();
        jlEmail1 = new javax.swing.JLabel();
        jtfEmail1 = new javax.swing.JTextField();
        jlDataNasc1 = new javax.swing.JLabel();
        jtfDataNasc1 = new javax.swing.JTextField();
        jlPeso1 = new javax.swing.JLabel();
        jtfPeso1 = new javax.swing.JTextField();
        jlAltura1 = new javax.swing.JLabel();
        jtfAltura1 = new javax.swing.JTextField();
        jlAlergias1 = new javax.swing.JLabel();
        jtfAlergias1 = new javax.swing.JTextField();
        jlDoencas1 = new javax.swing.JLabel();
        jtfDoencas1 = new javax.swing.JTextField();
        jbCadastrar1 = new javax.swing.JButton();
        jbCancelar1 = new javax.swing.JButton();

        jlNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlNome.setText("Nome Completo:");

        jtfNome.setPreferredSize(new java.awt.Dimension(250, 24));

        jlEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlEmail.setText("E-mail:");

        jtfEmail.setPreferredSize(new java.awt.Dimension(250, 24));

        jlDataNasc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlDataNasc.setText("Data de Nascimento:");

        jtfDataNasc.setPreferredSize(new java.awt.Dimension(100, 24));
        jtfDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataNascActionPerformed(evt);
            }
        });

        jlPeso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlPeso.setText("Peso:");

        jtfPeso.setPreferredSize(new java.awt.Dimension(60, 24));

        jlAltura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlAltura.setText("Altura:");

        jtfAltura.setPreferredSize(new java.awt.Dimension(60, 24));

        jlAlergias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlAlergias.setText("Alergias:");

        jtfAlergias.setPreferredSize(new java.awt.Dimension(250, 24));

        jlDoencas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlDoencas.setText("Doenças:");

        jtfDoencas.setPreferredSize(new java.awt.Dimension(250, 24));

        jbCadastrar.setBackground(new java.awt.Color(47, 85, 123));
        jbCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.setPreferredSize(new java.awt.Dimension(100, 26));
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbCancelar.setBackground(new java.awt.Color(47, 85, 123));
        jbCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar.setText("Cancelar");
        jbCancelar.setPreferredSize(new java.awt.Dimension(100, 26));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("CADASTRO DE NOVO USUÁRIO");

        jlNome1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlNome1.setText("Nome Completo:");

        jtfNome1.setPreferredSize(new java.awt.Dimension(250, 24));
        jtfNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNome1ActionPerformed(evt);
            }
        });

        jlEmail1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlEmail1.setText("E-mail:");

        jtfEmail1.setPreferredSize(new java.awt.Dimension(250, 24));

        jlDataNasc1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlDataNasc1.setText("Data de Nascimento:");

        jtfDataNasc1.setPreferredSize(new java.awt.Dimension(100, 24));
        jtfDataNasc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataNasc1ActionPerformed(evt);
            }
        });

        jlPeso1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlPeso1.setText("Peso:");

        jtfPeso1.setPreferredSize(new java.awt.Dimension(60, 24));

        jlAltura1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlAltura1.setText("Altura:");

        jtfAltura1.setPreferredSize(new java.awt.Dimension(60, 24));

        jlAlergias1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlAlergias1.setText("Alergias:");

        jtfAlergias1.setPreferredSize(new java.awt.Dimension(250, 24));

        jlDoencas1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlDoencas1.setText("Doenças:");

        jtfDoencas1.setPreferredSize(new java.awt.Dimension(250, 24));

        jbCadastrar1.setBackground(new java.awt.Color(47, 85, 123));
        jbCadastrar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCadastrar1.setForeground(new java.awt.Color(255, 255, 255));
        jbCadastrar1.setText("Cadastrar");
        jbCadastrar1.setPreferredSize(new java.awt.Dimension(100, 26));
        jbCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrar1ActionPerformed(evt);
            }
        });

        jbCancelar1.setBackground(new java.awt.Color(47, 85, 123));
        jbCancelar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar1.setText("Cancelar");
        jbCancelar1.setPreferredSize(new java.awt.Dimension(100, 26));
        jbCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jbCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlDoencas1)
                        .addComponent(jlAlergias1)
                        .addComponent(jlAltura1)
                        .addComponent(jlPeso1)
                        .addComponent(jlDataNasc1)
                        .addComponent(jlEmail1)
                        .addComponent(jlNome1))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfDataNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfAlergias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfDoencas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(159, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlNome1)
                        .addComponent(jtfNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlEmail1)
                        .addComponent(jtfEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlDataNasc1)
                        .addComponent(jtfDataNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlPeso1)
                        .addComponent(jtfPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlAltura1)
                        .addComponent(jtfAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlAlergias1)
                        .addComponent(jtfAlergias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlDoencas1)
                        .addComponent(jtfDoencas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(134, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataNascActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtfDataNasc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataNasc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataNasc1ActionPerformed

    private void jtfNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNome1ActionPerformed

    private void jbCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrar1ActionPerformed
        // TODO add your handling code here:
        cadastrarUsuario();
        cancelar();
    }//GEN-LAST:event_jbCadastrar1ActionPerformed

    private void jbCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelar1ActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_jbCancelar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCadastrar1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCancelar1;
    private javax.swing.JLabel jlAlergias;
    private javax.swing.JLabel jlAlergias1;
    private javax.swing.JLabel jlAltura;
    private javax.swing.JLabel jlAltura1;
    private javax.swing.JLabel jlDataNasc;
    private javax.swing.JLabel jlDataNasc1;
    private javax.swing.JLabel jlDoencas;
    private javax.swing.JLabel jlDoencas1;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEmail1;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNome1;
    private javax.swing.JLabel jlPeso;
    private javax.swing.JLabel jlPeso1;
    private javax.swing.JTextField jtfAlergias;
    private javax.swing.JTextField jtfAlergias1;
    private javax.swing.JTextField jtfAltura;
    private javax.swing.JTextField jtfAltura1;
    private javax.swing.JTextField jtfDataNasc;
    private javax.swing.JTextField jtfDataNasc1;
    private javax.swing.JTextField jtfDoencas;
    private javax.swing.JTextField jtfDoencas1;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEmail1;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNome1;
    private javax.swing.JTextField jtfPeso;
    private javax.swing.JTextField jtfPeso1;
    // End of variables declaration//GEN-END:variables
}
