/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author thiag
 */
public class GUICheckinFrame extends javax.swing.JFrame {

    /**
     * Creates new form GUICheckinFrame
     */
    public GUICheckinFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlMostra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbCheckPositivo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jlMostra.setText("jLabel9");
        jPanel1.add(jlMostra);
        jlMostra.setBounds(0, 0, 700, 500);

        jLabel1.setText("Olá Thiago");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(24, 11, 51, 14);

        jLabel2.setText("Configurações da conta");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(558, 11, 114, 14);

        jButton1.setText("CHECK IN PESSOAL DIÁRIO");
        jButton1.setEnabled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(240, 40));
        jPanel1.add(jButton1);
        jButton1.setBounds(93, 43, 240, 40);

        jButton2.setText("MAPA DE CONTAMINAÇÃO");
        jButton2.setPreferredSize(new java.awt.Dimension(240, 40));
        jPanel1.add(jButton2);
        jButton2.setBounds(359, 43, 240, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("CHECK IN PESSOAL DIÁRIO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(198, 117, 252, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Como você está se sentindo hoje?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(201, 168, 271, 22);

        jButton3.setBackground(new java.awt.Color(153, 255, 102));
        jButton3.setText("Me sinto bem, nenhum sintoma");
        jButton3.setPreferredSize(new java.awt.Dimension(300, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(192, 229, 300, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("SINTO UM OU MAIS DOS SEGUINTES SINTOMAS:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(201, 305, 291, 15);

        jLabel6.setText("Febre alta (acima de 39 graus)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 345, 147, 14);

        jLabel7.setText("Tosse seca e constante");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 373, 113, 14);

        jLabel8.setText("Dificuldade para respirar");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(260, 400, 117, 14);

        jbCheckPositivo.setBackground(new java.awt.Color(255, 51, 51));
        jbCheckPositivo.setForeground(new java.awt.Color(255, 255, 255));
        jbCheckPositivo.setText("Reportar sintomas de Covid-19");
        jbCheckPositivo.setPreferredSize(new java.awt.Dimension(250, 40));
        jbCheckPositivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCheckPositivoActionPerformed(evt);
            }
        });
        jPanel1.add(jbCheckPositivo);
        jbCheckPositivo.setBounds(204, 432, 250, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(34, 201, 611, 10);
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(233, 338, 21, 21);
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(233, 366, 21, 21);
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(233, 393, 21, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        GUINegativo gneg = new GUINegativo();
        jlMostra.add(gneg);
        gneg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbCheckPositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCheckPositivoActionPerformed
        // TODO add your handling code here:

        /*
        GUICheckin gcheck = new GUICheckin();
        jlDisplay.add(gcheck);
        gcheck.setVisible(true);
        */
    }//GEN-LAST:event_jbCheckPositivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICheckinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICheckinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICheckinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICheckinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICheckinFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCheckPositivo;
    private javax.swing.JLabel jlMostra;
    // End of variables declaration//GEN-END:variables
}
