/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.mysql.cj.protocol.Resultset;
import dao.UsuarioDAO;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import modelo.Adm;


/**
 *
 * @author jdsma
 */
public class GUILogin extends javax.swing.JFrame {

    /**
     * Creates new form GUILogin
     */
    public GUILogin() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrar = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelUser = new javax.swing.JLabel();
        jLabelMensagenAbertura = new javax.swing.JLabel();
        jLabelMensagenCadastrese = new javax.swing.JLabel();
        jLabelFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadastrar.setText("Cadastre-se");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar);
        jButtonCadastrar.setBounds(160, 280, 160, 30);

        jButtonEntrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar);
        jButtonEntrar.setBounds(160, 210, 160, 30);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(160, 150, 50, 20);

        jPasswordFieldSenha.setBackground(new java.awt.Color(204, 255, 255));
        jPasswordFieldSenha.setToolTipText("Digite sua senha.");
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(160, 170, 160, 30);

        jTextFieldUser.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldUser.setToolTipText("Digite usuário");
        getContentPane().add(jTextFieldUser);
        jTextFieldUser.setBounds(160, 120, 160, 30);

        jLabelUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelUser.setText("Usuário");
        getContentPane().add(jLabelUser);
        jLabelUser.setBounds(160, 90, 50, 30);

        jLabelMensagenAbertura.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelMensagenAbertura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensagenAbertura.setText("SISTEMA DE AUXÍLIO DA PREVENÇÃO E COMBATE AO COVIDE - 19");
        getContentPane().add(jLabelMensagenAbertura);
        jLabelMensagenAbertura.setBounds(50, 20, 370, 40);

        jLabelMensagenCadastrese.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMensagenCadastrese.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensagenCadastrese.setText("Ainda não está escrito ?");
        getContentPane().add(jLabelMensagenCadastrese);
        jLabelMensagenCadastrese.setBounds(160, 240, 170, 40);

        jLabelFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/papel_de_parede.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoTela);
        jLabelFundoTela.setBounds(0, 0, 470, 370);

        setSize(new java.awt.Dimension(487, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        CadastroUsuario cad = new CadastroUsuario();
        cad.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        /*try {
            
            String senha, nomeAcesso;
       
             senha = jPasswordFieldSenha.getText();
             nomeAcesso = jTextFieldUser.getText();
 
             Adm admin = new Adm();
             admin.setNomeAcesso(nomeAcesso);
             admin.setSenha(senha);

            /* PesquisaCadastro PesqCad = new PesquisaCadastro();
             PesqCad.setVisible(true);
             this.setVisible(false); 
            
             
             UsuarioDAO admin;
             admin = new UsuarioDAO();
             Resultset rsudao = admin.autenticarAdmin(admin);
        
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Freajdnsk" + erro);
        }
        */
        
        
        if(jTextFieldUser.getText().equals("adm")&&jPasswordFieldSenha.getText()
                .equals("master")){
            PesquisaCadastro PesqCad = new PesquisaCadastro();
            PesqCad.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Acesso Negado");
        }

        
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabelFundoTela;
    private javax.swing.JLabel jLabelMensagenAbertura;
    private javax.swing.JLabel jLabelMensagenCadastrese;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
