/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author thiag
 */
public class GUIPrimeiraTela extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrimeiraTela
     */
    public GUIPrimeiraTela() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAdmin = new javax.swing.JButton();
        jlTitulo2 = new javax.swing.JLabel();
        jlTitulo1 = new javax.swing.JLabel();
        jlTitulo3 = new javax.swing.JLabel();
        jlCreditos = new javax.swing.JLabel();
        jbIniciar = new javax.swing.JButton();
        jbCadastreSe = new javax.swing.JButton();
        jlAvisoCadastro = new javax.swing.JLabel();
        jlPlanoDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 840));
        getContentPane().setLayout(null);

        jbAdmin.setForeground(new java.awt.Color(0, 0, 102));
        jbAdmin.setText("Admin");
        jbAdmin.setPreferredSize(new java.awt.Dimension(100, 30));
        jbAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jbAdmin);
        jbAdmin.setBounds(700, 50, 100, 30);

        jlTitulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo2.setText("PREVENÇÃO E COMBATE AO");
        getContentPane().add(jlTitulo2);
        jlTitulo2.setBounds(40, 70, 290, 22);

        jlTitulo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo1.setText("SISTEMA DE AUXÍLIO DA");
        getContentPane().add(jlTitulo1);
        jlTitulo1.setBounds(40, 40, 280, 22);

        jlTitulo3.setBackground(new java.awt.Color(255, 255, 255));
        jlTitulo3.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        jlTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo3.setText("COVID-19");
        getContentPane().add(jlTitulo3);
        jlTitulo3.setBounds(310, 30, 320, 61);

        jlCreditos.setBackground(new java.awt.Color(0, 0, 102));
        jlCreditos.setForeground(new java.awt.Color(0, 0, 102));
        jlCreditos.setText("- Desenvolvido por Grupo 5 - Jaderson | Thiago");
        getContentPane().add(jlCreditos);
        jlCreditos.setBounds(180, 380, 270, 14);

        jbIniciar.setBackground(new java.awt.Color(0, 0, 51));
        jbIniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jbIniciar.setText("INICIAR");
        jbIniciar.setPreferredSize(new java.awt.Dimension(150, 40));
        jbIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jbIniciar);
        jbIniciar.setBounds(220, 140, 150, 40);

        jbCadastreSe.setBackground(new java.awt.Color(255, 255, 255));
        jbCadastreSe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbCadastreSe.setForeground(new java.awt.Color(0, 0, 102));
        jbCadastreSe.setText("CADASTRE-SE AQUI");
        jbCadastreSe.setPreferredSize(new java.awt.Dimension(150, 40));
        jbCadastreSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastreSeActionPerformed(evt);
            }
        });
        getContentPane().add(jbCadastreSe);
        jbCadastreSe.setBounds(200, 290, 200, 40);

        jlAvisoCadastro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlAvisoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jlAvisoCadastro.setText("Ainda não possui um usuário cadastrado?");
        getContentPane().add(jlAvisoCadastro);
        jlAvisoCadastro.setBounds(190, 260, 223, 15);

        jlPlanoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_abertura_v1.jpg"))); // NOI18N
        jlPlanoDeFundo.setPreferredSize(new java.awt.Dimension(1400, 840));
        getContentPane().add(jlPlanoDeFundo);
        jlPlanoDeFundo.setBounds(0, 0, 1400, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciarActionPerformed
        GUICheckInDiario gCheck = new GUICheckInDiario();
        gCheck.setVisible(true);
        
    }//GEN-LAST:event_jbIniciarActionPerformed

    private void jbCadastreSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastreSeActionPerformed
        GUINovoUsuario gcad = new GUINovoUsuario();
        gcad.setVisible(true);
    }//GEN-LAST:event_jbCadastreSeActionPerformed

    private void jbAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdminActionPerformed
        // TODO add your handling code here:
        GUILista gAdmin = new GUILista();
        gAdmin.setVisible(true);
    }//GEN-LAST:event_jbAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrimeiraTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAdmin;
    private javax.swing.JButton jbCadastreSe;
    private javax.swing.JButton jbIniciar;
    private javax.swing.JLabel jlAvisoCadastro;
    private javax.swing.JLabel jlCreditos;
    private javax.swing.JLabel jlPlanoDeFundo;
    private javax.swing.JLabel jlTitulo1;
    private javax.swing.JLabel jlTitulo2;
    private javax.swing.JLabel jlTitulo3;
    // End of variables declaration//GEN-END:variables
}
